export const newsCategories: {[key: string]: string[]} = {
  'Politics & Global Affairs': [
    'US Politics',
    'Indian Politics',
    'UK Politics',
    "China's Politics",
    "Russia's Geopolitics",
    'EU Politics',
    'War & Tensions',
    'Superpower Moves',
  ],
  'Business & Economy': [
    'VC & Funding',
    'Startups',
    'Stock Market',
    'Investment Trends',
    'Layoffs & Hires',
    'Corporate Deals',
  ],
  'Science and Technology': [
    'Artificial Intelligence & Machine Learning',
    'Software Development & Engineering',
    'Data Science',
    'Space Exploration & Astronomy',
    'Health & Biotech Innovations',
    'Cybersecurity & Data Privacy',
  ],
  'Health and Wellness': [
    'Medical Breakthroughs & Innovations',
    'Mental Health & Well-being',
    'Fitness & Exercise Trends',
    'Nutrition & Diet',
  ],
  Sports: [
    'Football',
    'Cricket',
    'Olympics & Major Events',
    'Basketball & NBA',
    'Esports & Gaming',
    'Badminton & Other Racquet Sports',
    'American Football & Rugby',
  ],
  'Entertainment and Celebrity News': [
    'Movies & TV Shows',
    'Celebrity Gossip & Lifestyle',
    'Music & Concerts',
    'Bollywood',
    'Hollywood',
    'K-Dramas',
  ],
  'Crime and Public Safety': ['Cybercrime & Online Scams'],
  'Human Interest Stories': ['Viral & Social Media Trends'],
};
